backend:
  name: github
  repo: affilirator/thekitchen-pot
  branch: main
  use_graphql: true
  # client_secret: 7f474a98bd6b11bd307723d6bc699e353dc0bca2

site_url: https://thekitchenpot.com
display_url: thekitchenpot.com
# logo_url: https://www.bestofvacuum.com/images/logo.svg
show_preview_links: true
publish_mode: editorial_workflow
media_folder: "src/content/blog/images"
public_folder: "/src/content/blog/images"

collections:
  - name: "blog"
    label: "WordPress Posts"
    label_singular: "Article"
    preview_path: "/blog/{{slug}}/"
    folder: "src/content/blog"
    description: "Blog posts imported from WordPress. Edits only - create new posts in 'New CMS Posts'."
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "hidden",
          default: "{{fields.pubDate}}",
        }
      - {
          label: "Source",
          name: "source",
          widget: "string",
          default: "wordpress",
        }
      - { label: "URL Slug", name: "slug", widget: "string", required: true }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogLayout.astro",
        }
      - {
          label: "Publication Date",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          label: "Modified Date",
          name: "modDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Description", name: "excerpt", widget: "text" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Show Table of Contents",
          name: "showTableOfContents",
          widget: "boolean",
          default: true,
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Bio", name: "authorBio", widget: "text" }
      - {
          label: "Author Image",
          name: "authorImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Author Image Alt Text",
          name: "authorImageAlt",
          widget: "string",
          required: false,
        }
      - {
          label: "Cover Alt Text",
          name: "coverAlt",
          widget: "string",
          required: false,
        }

  - name: "static-blog"
    label: "New Posts"
    label_singular: "Article"
    preview_path: "/blog/{{slug}}/"
    folder: "src/content/blog"
    media_folder: "src/content/blog/images"
    public_folder: "/images/blog"
    filter: { field: "source", value: "decap" }
    description: "New articles added via CMS"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: [".{20,}", "Must have at least 20 characters"],
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
          pattern: ["^[a-zA-Z0-9-]+$", "Only alphanumeric and hyphens allowed"],
          hint: "Auto-generated from title (editable)",
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogLayout.astro",
        }
      - {
          label: "Publication Date",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          label: "Modified Date",
          name: "modDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          default: "{{now}}",
        }
      - {
          label: "Post Author",
          name: "postAuthor",
          widget: "relation",
          collection: "authors",
          search_fields: ["author", "slug"],
          value_field: "slug",
          display_fields: ["author", "authorBio"],
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Optimal size: 1200x630px",
        }
      - {
          label: "Description",
          name: "excerpt",
          widget: "text",
          pattern: [".{50,160}", "SEO description (50-160 characters)"],
        }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          search_fields: ["slug"],
          value_field: "slug",
          display_fields: ["slug", "name"],
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          field: { label: "Tag", name: "tag", widget: "string" },
          max: 3,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Source",
          name: "source",
          widget: "hidden",
          default: "decap",
          hint: "Content origin - do not modify",
        }

  - name: "legalpages"
    label: "Legal Pages"
    publish: false
    files:
      - name: "privacy_policy"
        label: "Privacy Policy"
        file: "src/content/legal/privacy-policy.md"
        fields:
          - { name: "title", label: "Page Title", widget: "string" }
          - { name: "last_updated", label: "Last Updated", widget: "datetime" }
          - name: "sections"
            label: "Policy Sections"
            widget: "list"
            fields:
              - { name: "id", label: "Section ID", widget: "string" }
              - { name: "title", label: "Section Title", widget: "string" }
              - { name: "content", label: "Content", widget: "markdown" }
          - name: "contact"
            label: "Contact Information"
            widget: "object"
            fields:
              - { name: "email", label: "Contact Email", widget: "string" }
              - { name: "address", label: "Mailing Address", widget: "text" }

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "src/content/categories"
    identifier_field: "slug"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ["^[a-zA-Z0-9-]+$", "Alphanumeric and hyphens only"],
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }

  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    identifier_field: "slug"
    slug: "{{slug}}"
    create: true
    fields:
      - {
          label: "Full Name",
          name: "author",
          widget: "string",
          pattern: [".{3,}", "Minimum 3 characters"],
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ["^[a-zA-Z0-9-]+$", "Alphanumeric and hyphens only"],
        }
      - {
          label: "Short Bio",
          name: "authorBio",
          widget: "text",
          pattern: [".{50,500}", "50-500 characters"],
        }
      - {
          label: "Profile Image",
          name: "authorImage",
          widget: "image",
          media_folder: "/public/images/authors",
          public_folder: "/images/authors",
          hint: "1:1 ratio recommended",
        }
      - { label: "Professional Title", name: "title", widget: "string" }
      - {
          label: "Expertise Areas",
          name: "expertise",
          widget: "list",
          field: { label: "Area", name: "area", widget: "string" },
          max: 5,
        }
      - label: "Credentials"
        name: "credentials"
        widget: "list"
        #summary: '{{fields.quote}} - {{fields.author.name}}'
        fields:
          - {
              label: Qualification,
              name: qualification,
              widget: string,
              default: "Masters in my Field",
            }
          - label: Institution
            name: institution
            widget: object
            fields:
              - {
                  label: Name,
                  name: name,
                  widget: string,
                  default: "University of Example",
                }
              - {
                  label: Location,
                  name: location,
                  widget: string,
                  default: "City, Country",
                }
          - label: Year
            name: year
            widget: number

      - {
          label: "Years Experience",
          name: "yearsOfExperience",
          widget: "number",
          min: 0,
          max: 100,
        }
      - { label: "Detailed Bio", name: "longBio", widget: "markdown" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - { label: "Source", name: "src", widget: "string" }
          - { label: "Alt Text", name: "alt", widget: "string" }
        default:
          - { src: "/img/tennis.jpg", alt: "Tennis" }
          - { src: "/img/footbar.jpg", alt: "Football" }

      - {
          label: "Schema Type",
          name: "schemaType",
          widget: "select",
          options: ["Person", "Journalist", "Researcher"],
          default: "Person",
        }

  - name: "reviews"
    label: "Reviews"
    label_singular: "Review"
    folder: "src/content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/MainLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ["^[a-zA-Z0-9-]+$", "Alphanumeric and hyphens only"],
        }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Publication Date", name: "date", widget: "datetime" }
      - {
          label: "Modified Date",
          name: "modDate",
          widget: "datetime",
          default: "{{now}}",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["author", "slug"],
          value_field: "slug",
          display_fields: ["author", "authorBio"],
        }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          search_fields: ["slug"],
          value_field: "slug",
          display_fields: ["slug", "name"],
        }
      - name: "product"
        label: "Product Details"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Brand", name: "brand", widget: "string" }
          - { label: "Model", name: "model", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Price",
              name: "price",
              widget: "number",
              value_type: "float",
            }
          - { label: "Product URL", name: "url", widget: "string" }
          - { label: "Features", name: "features", widget: "list" }
          - name: "specs"
            label: "Specifications"
            widget: "object"
            fields:
              - { label: "Dimensions", name: "dimensions", widget: "string" }
              - { label: "Weight", name: "weight", widget: "string" }
              - { label: "Battery Life", name: "batteryLife", widget: "string" }
      - name: "rating"
        label: "Ratings"
        widget: "object"
        fields:
          - {
              label: "Overall",
              name: "overall",
              widget: "number",
              min: 0,
              max: 5,
              step: 0.1,
            }
          - {
              label: "Value",
              name: "valueForMoney",
              widget: "number",
              min: 0,
              max: 5,
              step: 0.1,
            }
      - { label: "Pros", name: "pros", widget: "list" }
      - { label: "Cons", name: "cons", widget: "list" }
      - { label: "Verdict", name: "verdict", widget: "text" }

  - name: "team"
    label: "Team Members"
    folder: "src/content/team"
    create: true
    slug: "{{name | slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Founded Year", name: "foundedYear", widget: "number" }
          - { label: "Content", name: "body", widget: "markdown" }

      - file: "src/content/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - name: "officeHours"
            label: "Office Hours"
            widget: "list"
            fields:
              - { label: "Day", name: "day", widget: "string" }
              - { label: "Hours", name: "hours", widget: "string" }
